/**
 * This class represent a file as a note
 * to create a note you must provide its directory location and its name
 */

package notepad0;

import java.io.*;

public class Note extends File
{
    private static final long serialVersionUID = -5287441771627923507L; // autogenerated

    // File(File parent, String child)
    Note(File directory, String fileName)
    {
        super(directory, fileName);
    }

    // File(String parent, String child)
    Note(String directory, String fileName)
    {
        super(directory, fileName);
    }
}